### ISSUE TITLE
cant play with video

### ISSUE THREAD

**Issue by seekerquoc** [andrewssobral/simple_vehicle_counting#3]
it alwayls give me error, cant open video, can you help me?

**Comment by zshn25** [comment]
Same, Please help. It says Can't open Video!. I'm using VS2013. I guess this program doesn't reqquire OpenCV2.4 to be installed. I have OpenCV3.0 by the way.
![image](https://cloud.githubusercontent.com/assets/5270999/12005229/465e66ca-abbf-11e5-9f70-96ff0384f7bc.png)

I tried to use ```VideoCapture capture("dataset/video.avi");``` instead of ```CvCapture *capture = 0;
  capture = cvCaptureFromAVI("dataset/video.avi");```. But, I get this error
```
IntelliSense: identifier "VideoCapture" is undefined
```

**Comment by aubryll** [comment]
download klite, it comes with alll necessary codecs, I had the same issue too until i installed klite

**Comment by andrewssobral** [comment]
Hi @seekerquoc and @zshn25 , please put the opencv_ffmpeg2410.dll (for OpenCV 2.4.10) or related file for OpenCV3 in your project folder. Another solution is to put the OpenCV **bin** folder in your system path.
